### ISSUE TITLE
Nok off homebridge

### ISSUE THREAD

**Issue by dragonjo84** [NebzHB/jeedom_docs#8]
Bonjour
J’ai un souci avec le NOK qui reste off malgré des reconfigurations...
J’ai essayé ça a marche. Bien reconnu sur mon iPhone. Mais j’avais omis d’installer le plugin ewelink. J’ai donc supprimé le concentrateur dans mon appli. Voulu le relancer mais le NOK ne tient pas... merci pour votre aide 

Désolé si le fichier est très volumineux...
[1/17/2020, 5:00:59 PM] Loaded config.json with 0 accessories and 1 platforms.
[1/17/2020, 5:00:59 PM] ---
[1/17/2020, 5:01:00 PM] Loaded plugin: homebridge-alexa
[1/17/2020, 5:01:00 PM] Registering platform 'homebridge-alexa.Alexa'
[1/17/2020, 5:01:00 PM] ---
[1/17/2020, 5:01:02 PM] Loaded plugin: homebridge-camera-ffmpeg
[1/17/2020, 5:01:02 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[1/17/2020, 5:01:02 PM] ---
[1/17/2020, 5:01:02 PM] Loaded plugin: homebridge-jeedom
[1/17/2020, 5:01:02 PM] Registering platform 'homebridge-jeedom.Jeedom'
[1/17/2020, 5:01:02 PM] ---
[1/17/2020, 5:01:02 PM] Loaded plugin: homebridge-ewelink
homebridge API version: 2.4
[1/17/2020, 5:01:02 PM] Registering platform 'homebridge-eWeLink.eWeLink'
[1/17/2020, 5:01:02 PM] ---
[1/17/2020, 5:01:02 PM] Loading 1 platforms...
[1/17/2020, 5:01:02 PM] [Jeedom Delta_Repaired_9c] Initializing Jeedom platform...
[1/17/2020, 5:01:02 PM] [Jeedom Delta_Repaired_9c] debugLevel:400
Load homebridge-camera-ffmpeg.Camera-ffmpeg
Load homebridge-eWeLink.eWeLink
[1/17/2020, 5:01:02 PM] [homebridge-eWeLink.eWeLink] Intialising eWeLink
[1/17/2020, 5:01:02 PM] TypeError: Cannot read property 'authenticationToken' of null
at new eWeLink (/usr/local/lib/node_modules/homebridge-ewelink/index.js:42:38)
at Server._loadDynamicPlatforms (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/server.js:358:30)
at Server.run (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/server.js:92:8)
at module.exports (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/cli.js:59:10)
at Object.<anonymous> (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (internal/modules/cjs/loader.js:955:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
at Module.load (internal/modules/cjs/loader.js:811:32)
at Function.Module._load (internal/modules/cjs/loader.js:723:14)
at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
[1/17/2020, 5:01:02 PM] Got SIGTERM, shutting down Homebridge...
[1/17/2020, 5:02:12 PM] Loaded config.json with 0 accessories and 1 platforms.
[1/17/2020, 5:02:12 PM] ---
[1/17/2020, 5:02:13 PM] Loaded plugin: homebridge-alexa
[1/17/2020, 5:02:13 PM] Registering platform 'homebridge-alexa.Alexa'
[1/17/2020, 5:02:13 PM] ---
[1/17/2020, 5:02:14 PM] Loaded plugin: homebridge-camera-ffmpeg
[1/17/2020, 5:02:14 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[1/17/2020, 5:02:14 PM] ---
[1/17/2020, 5:02:14 PM] Loaded plugin: homebridge-jeedom
[1/17/2020, 5:02:14 PM] Registering platform 'homebridge-jeedom.Jeedom'
[1/17/2020, 5:02:14 PM] ---
[1/17/2020, 5:02:14 PM] Loaded plugin: homebridge-ewelink
homebridge API version: 2.4
[1/17/2020, 5:02:14 PM] Registering platform 'homebridge-eWeLink.eWeLink'
[1/17/2020, 5:02:14 PM] ---
[1/17/2020, 5:02:14 PM] Loading 1 platforms...
[1/17/2020, 5:02:14 PM] [Jeedom Delta_Repaired_9c] Initializing Jeedom platform...
[1/17/2020, 5:02:14 PM] [Jeedom Delta_Repaired_9c] debugLevel:400
Load homebridge-camera-ffmpeg.Camera-ffmpeg
Load homebridge-eWeLink.eWeLink
[1/17/2020, 5:02:14 PM] [homebridge-eWeLink.eWeLink] Intialising eWeLink
[1/17/2020, 5:02:14 PM] TypeError: Cannot read property 'authenticationToken' of null
at new eWeLink (/usr/local/lib/node_modules/homebridge-ewelink/index.js:42:38)
at Server._loadDynamicPlatforms (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/server.js:358:30)
at Server.run (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/server.js:92:8)
at module.exports (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/cli.js:59:10)
at Object.<anonymous> (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (internal/modules/cjs/loader.js:955:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
at Module.load (internal/modules/cjs/loader.js:811:32)
at Function.Module._load (internal/modules/cjs/loader.js:723:14)
at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
[1/17/2020, 5:02:14 PM] Got SIGTERM, shutting down Homebridge...
[1/17/2020, 5:03:36 PM] Loaded config.json with 0 accessories and 1 platforms.
[1/17/2020, 5:03:36 PM] ---
[1/17/2020, 5:03:37 PM] Loaded plugin: homebridge-alexa
[1/17/2020, 5:03:37 PM] Registering platform 'homebridge-alexa.Alexa'
[1/17/2020, 5:03:37 PM] ---
[1/17/2020, 5:03:38 PM] Loaded plugin: homebridge-camera-ffmpeg
[1/17/2020, 5:03:38 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[1/17/2020, 5:03:38 PM] ---
[1/17/2020, 5:03:38 PM] Loaded plugin: homebridge-jeedom
[1/17/2020, 5:03:38 PM] Registering platform 'homebridge-jeedom.Jeedom'
[1/17/2020, 5:03:38 PM] ---
[1/17/2020, 5:03:38 PM] Loaded plugin: homebridge-ewelink
homebridge API version: 2.4
[1/17/2020, 5:03:38 PM] Registering platform 'homebridge-eWeLink.eWeLink'
[1/17/2020, 5:03:38 PM] ---
[1/17/2020, 5:03:38 PM] Loading 1 platforms...
[1/17/2020, 5:03:38 PM] [Jeedom Delta_Repaired_9c] Initializing Jeedom platform...
[1/17/2020, 5:03:38 PM] [Jeedom Delta_Repaired_9c] debugLevel:400
Load homebridge-camera-ffmpeg.Camera-ffmpeg
Load homebridge-eWeLink.eWeLink
[1/17/2020, 5:03:38 PM] [homebridge-eWeLink.eWeLink] Intialising eWeLink
[1/17/2020, 5:03:38 PM] TypeError: Cannot read property 'authenticationToken' of null
at new eWeLink (/usr/local/lib/node_modules/homebridge-ewelink/index.js:42:38)
at Server._loadDynamicPlatforms (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/server.js:358:30)
at Server.run (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/server.js:92:8)
at module.exports (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/cli.js:59:10)
at Object.<anonymous> (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (internal/modules/cjs/loader.js:955:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
at Module.load (internal/modules/cjs/loader.js:811:32)
at Function.Module._load (internal/modules/cjs/loader.js:723:14)
at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
[1/17/2020, 5:03:38 PM] Got SIGTERM, shutting down Homebridge...
[1/17/2020, 5:04:36 PM] Loaded config.json with 0 accessories and 1 platforms.
[1/17/2020, 5:04:36 PM] ---
[1/17/2020, 5:04:37 PM] Loaded plugin: homebridge-alexa
[1/17/2020, 5:04:37 PM] Registering platform 'homebridge-alexa.Alexa'
[1/17/2020, 5:04:37 PM] ---
[1/17/2020, 5:04:38 PM] Loaded plugin: homebridge-camera-ffmpeg
[1/17/2020, 5:04:38 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[1/17/2020, 5:04:38 PM] ---
[1/17/2020, 5:04:38 PM] Loaded plugin: homebridge-jeedom
[1/17/2020, 5:04:38 PM] Registering platform 'homebridge-jeedom.Jeedom'
[1/17/2020, 5:04:38 PM] ---
[1/17/2020, 5:04:39 PM] Loaded plugin: homebridge-ewelink
homebridge API version: 2.4
[1/17/2020, 5:04:39 PM] Registering platform 'homebridge-eWeLink.eWeLink'
[1/17/2020, 5:04:39 PM] ---
[1/17/2020, 5:04:39 PM] Loading 1 platforms...
[1/17/2020, 5:04:39 PM] [Jeedom Delta_Repaired_9c] Initializing Jeedom platform...
[1/17/2020, 5:04:39 PM] [Jeedom Delta_Repaired_9c] debugLevel:400
Load homebridge-camera-ffmpeg.Camera-ffmpeg
Load homebridge-eWeLink.eWeLink
[1/17/2020, 5:04:39 PM] [homebridge-eWeLink.eWeLink] Intialising eWeLink
[1/17/2020, 5:04:39 PM] TypeError: Cannot read property 'authenticationToken' of null
at new eWeLink (/usr/local/lib/node_modules/homebridge-ewelink/index.js:42:38)
at Server._loadDynamicPlatforms (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/server.js:358:30)
at Server.run (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/server.js:92:8)
at module.exports (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/cli.js:59:10)
at Object.<anonymous> (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (internal/modules/cjs/loader.js:955:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
at Module.load (internal/modules/cjs/loader.js:811:32)
at Function.Module._load (internal/modules/cjs/loader.js:723:14)
at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
[1/17/2020, 5:04:39 PM] Got SIGTERM, shutting down Homebridge...
[1/17/2020, 5:07:50 PM] Loaded config.json with 0 accessories and 1 platforms.
[1/17/2020, 5:07:50 PM] ---
[1/17/2020, 5:07:51 PM] Loaded plugin: homebridge-alexa
[1/17/2020, 5:07:51 PM] Registering platform 'homebridge-alexa.Alexa'
[1/17/2020, 5:07:51 PM] ---
[1/17/2020, 5:07:52 PM] Loaded plugin: homebridge-camera-ffmpeg
[1/17/2020, 5:07:52 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[1/17/2020, 5:07:52 PM] ---
[1/17/2020, 5:07:52 PM] Loaded plugin: homebridge-jeedom
[1/17/2020, 5:07:53 PM] Registering platform 'homebridge-jeedom.Jeedom'
[1/17/2020, 5:07:53 PM] ---
[1/17/2020, 5:07:53 PM] Loaded plugin: homebridge-ewelink
homebridge API version: 2.4
[1/17/2020, 5:07:53 PM] Registering platform 'homebridge-eWeLink.eWeLink'
[1/17/2020, 5:07:53 PM] ---
[1/17/2020, 5:07:53 PM] Loaded plugin: homebridge-tahoma
homebridge-tahoma API version: 2.4
[1/17/2020, 5:07:53 PM] Registering platform 'homebridge-tahoma.Tahoma'
[1/17/2020, 5:07:53 PM] ---
[1/17/2020, 5:07:53 PM] Loading 1 platforms...
[1/17/2020, 5:07:53 PM] [Jeedom Delta] Initializing Jeedom platform...
[1/17/2020, 5:07:53 PM] [Jeedom Delta] debugLevel:400
Load homebridge-camera-ffmpeg.Camera-ffmpeg
Load homebridge-eWeLink.eWeLink
[1/17/2020, 5:07:53 PM] [homebridge-eWeLink.eWeLink] Intialising eWeLink
[1/17/2020, 5:07:53 PM] TypeError: Cannot read property 'authenticationToken' of null
at new eWeLink (/usr/local/lib/node_modules/homebridge-ewelink/index.js:42:38)
at Server._loadDynamicPlatforms (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/server.js:358:30)
at Server.run (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/server.js:92:8)
at module.exports (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/cli.js:59:10)
at Object.<anonymous> (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (internal/modules/cjs/loader.js:955:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
at Module.load (internal/modules/cjs/loader.js:811:32)
at Function.Module._load (internal/modules/cjs/loader.js:723:14)
at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
[1/17/2020, 5:07:53 PM] Got SIGTERM, shutting down Homebridge...
[1/17/2020, 5:15:04 PM] Loaded config.json with 0 accessories and 1 platforms.
[1/17/2020, 5:15:05 PM] ---
[1/17/2020, 5:15:06 PM] Loaded plugin: homebridge-alexa
[1/17/2020, 5:15:06 PM] Registering platform 'homebridge-alexa.Alexa'
[1/17/2020, 5:15:06 PM] ---
[1/17/2020, 5:15:07 PM] Loaded plugin: homebridge-camera-ffmpeg
[1/17/2020, 5:15:07 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[1/17/2020, 5:15:07 PM] ---
[1/17/2020, 5:15:07 PM] Loaded plugin: homebridge-jeedom
[1/17/2020, 5:15:07 PM] Registering platform 'homebridge-jeedom.Jeedom'
[1/17/2020, 5:15:07 PM] ---
[1/17/2020, 5:15:08 PM] Loaded plugin: homebridge-ewelink-max
homebridge API version: 2.4
[1/17/2020, 5:15:08 PM] Registering platform 'homebridge-eWeLink.eWeLink'
[1/17/2020, 5:15:08 PM] ---
[1/17/2020, 5:15:08 PM] Loading 1 platforms...
[1/17/2020, 5:15:08 PM] [Jeedom Delta_Repaired_8b] Initializing Jeedom platform...
[1/17/2020, 5:15:08 PM] [Jeedom Delta_Repaired_8b] debugLevel:400
Load homebridge-camera-ffmpeg.Camera-ffmpeg
Load homebridge-eWeLink.eWeLink
[1/17/2020, 5:15:08 PM] TypeError: Cannot read property 'authenticationToken' of null
at new eWeLink (/usr/lib/node_modules/homebridge-ewelink-max/index.js:42:38)
at Server._loadDynamicPlatforms (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/server.js:358:30)
at Server.run (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/server.js:92:8)
at module.exports (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/cli.js:59:10)
at Object.<anonymous> (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (internal/modules/cjs/loader.js:955:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
at Module.load (internal/modules/cjs/loader.js:811:32)
at Function.Module._load (internal/modules/cjs/loader.js:723:14)
at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
[1/17/2020, 5:15:08 PM] Got SIGTERM, shutting down Homebridge...
[1/17/2020, 5:17:06 PM] Loaded config.json with 0 accessories and 1 platforms.
[1/17/2020, 5:17:06 PM] ---
[1/17/2020, 5:17:07 PM] Loaded plugin: homebridge-alexa
[1/17/2020, 5:17:07 PM] Registering platform 'homebridge-alexa.Alexa'
[1/17/2020, 5:17:07 PM] ---
[1/17/2020, 5:17:08 PM] Loaded plugin: homebridge-camera-ffmpeg
[1/17/2020, 5:17:08 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[1/17/2020, 5:17:08 PM] ---
[1/17/2020, 5:17:08 PM] Loaded plugin: homebridge-jeedom
[1/17/2020, 5:17:08 PM] Registering platform 'homebridge-jeedom.Jeedom'
[1/17/2020, 5:17:08 PM] ---
[1/17/2020, 5:17:09 PM] Loaded plugin: homebridge-ewelink-max
homebridge API version: 2.4
[1/17/2020, 5:17:09 PM] Registering platform 'homebridge-eWeLink.eWeLink'
[1/17/2020, 5:17:09 PM] ---
[1/17/2020, 5:17:09 PM] Loading 1 platforms...
[1/17/2020, 5:17:09 PM] [Jeedom Delta] Initializing Jeedom platform...
[1/17/2020, 5:17:09 PM] [Jeedom Delta] debugLevel:400
Load homebridge-camera-ffmpeg.Camera-ffmpeg
Load homebridge-eWeLink.eWeLink
[1/17/2020, 5:17:09 PM] TypeError: Cannot read property 'authenticationToken' of null
at new eWeLink (/usr/lib/node_modules/homebridge-ewelink-max/index.js:42:38)
at Server._loadDynamicPlatforms (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/server.js:358:30)
at Server.run (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/server.js:92:8)
at module.exports (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/cli.js:59:10)
at Object.<anonymous> (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (internal/modules/cjs/loader.js:955:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
at Module.load (internal/modules/cjs/loader.js:811:32)
at Function.Module._load (internal/modules/cjs/loader.js:723:14)
at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
[1/17/2020, 5:17:09 PM] Got SIGTERM, shutting down Homebridge...
[1/17/2020, 5:20:04 PM] Loaded config.json with 0 accessories and 1 platforms.
[1/17/2020, 5:20:04 PM] ---
[1/17/2020, 5:20:06 PM] Loaded plugin: homebridge-alexa
[1/17/2020, 5:20:06 PM] Registering platform 'homebridge-alexa.Alexa'
[1/17/2020, 5:20:06 PM] ---
[1/17/2020, 5:20:07 PM] Loaded plugin: homebridge-camera-ffmpeg
[1/17/2020, 5:20:07 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[1/17/2020, 5:20:07 PM] ---
[1/17/2020, 5:20:07 PM] Loaded plugin: homebridge-jeedom
[1/17/2020, 5:20:07 PM] Registering platform 'homebridge-jeedom.Jeedom'
[1/17/2020, 5:20:07 PM] ---
[1/17/2020, 5:20:07 PM] Loaded plugin: homebridge-ewelink-max
homebridge API version: 2.4
[1/17/2020, 5:20:07 PM] Registering platform 'homebridge-eWeLink.eWeLink'
[1/17/2020, 5:20:07 PM] ---
[1/17/2020, 5:20:07 PM] Loading 1 platforms...
[1/17/2020, 5:20:07 PM] [Jeedom Delta] Initializing Jeedom platform...
[1/17/2020, 5:20:07 PM] [Jeedom Delta] debugLevel:400
Load homebridge-camera-ffmpeg.Camera-ffmpeg
Load homebridge-eWeLink.eWeLink
[1/17/2020, 5:20:07 PM] TypeError: Cannot read property 'authenticationToken' of null
at new eWeLink (/usr/lib/node_modules/homebridge-ewelink-max/index.js:42:38)
at Server._loadDynamicPlatforms (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/server.js:358:30)
at Server.run (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/server.js:92:8)
at module.exports (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/cli.js:59:10)
at Object.<anonymous> (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (internal/modules/cjs/loader.js:955:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
at Module.load (internal/modules/cjs/loader.js:811:32)
at Function.Module._load (internal/modules/cjs/loader.js:723:14)
at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
[1/17/2020, 5:20:07 PM] Got SIGTERM, shutting down Homebridge...
[1/17/2020, 5:25:03 PM] Loaded config.json with 0 accessories and 1 platforms.
[1/17/2020, 5:25:04 PM] ---
[1/17/2020, 5:25:05 PM] Loaded plugin: homebridge-alexa
[1/17/2020, 5:25:05 PM] Registering platform 'homebridge-alexa.Alexa'
[1/17/2020, 5:25:05 PM] ---
[1/17/2020, 5:25:06 PM] Loaded plugin: homebridge-camera-ffmpeg
[1/17/2020, 5:25:06 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[1/17/2020, 5:25:06 PM] ---
[1/17/2020, 5:25:06 PM] Loaded plugin: homebridge-jeedom
[1/17/2020, 5:25:06 PM] Registering platform 'homebridge-jeedom.Jeedom'
[1/17/2020, 5:25:06 PM] ---
[1/17/2020, 5:25:06 PM] Loaded plugin: homebridge-ewelink-max
homebridge API version: 2.4
[1/17/2020, 5:25:06 PM] Registering platform 'homebridge-eWeLink.eWeLink'
[1/17/2020, 5:25:06 PM] ---
[1/17/2020, 5:25:06 PM] Loading 1 platforms...
[1/17/2020, 5:25:06 PM] [Jeedom Delta] Initializing Jeedom platform...
[1/17/2020, 5:25:06 PM] [Jeedom Delta] debugLevel:400
Load homebridge-camera-ffmpeg.Camera-ffmpeg
Load homebridge-eWeLink.eWeLink
[1/17/2020, 5:25:06 PM] TypeError: Cannot read property 'authenticationToken' of null
at new eWeLink (/usr/lib/node_modules/homebridge-ewelink-max/index.js:42:38)
at Server._loadDynamicPlatforms (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/server.js:358:30)
at Server.run (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/server.js:92:8)
at module.exports (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/lib/cli.js:59:10)
at Object.<anonymous> (/var/www/html/plugins/homebridge/resources/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (internal/modules/cjs/loader.js:955:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
at Module.load (internal/modules/cjs/loader.js:811:32)
at Function.Module._load (internal/modules/cjs/loader.js:723:14)
at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
[1/17/2020, 5:25:06 PM] Got SIGTERM, shutting down Homebridge...

**Comment by NebzHB** [comment]
Bonjour,

si vous retirez un plugin, il faut également retirer sa configuration dans les plateformes supplémentaires (ou accessoires supplémentaires)

**Comment by dragonjo84** [comment]
En faite je voulais y installer le plugin mais quand il est en route le NOK de homebridge reste Off. 
J’ai réussi à les faire reconnaître dans le plugin en les installant en matériel générique mais pour allumer les interrupteurs il m’affiche 2 boutons un pour le On un pour le Off. J’aurai aimé que ça me mette un bouton comme les lampes Hue ou j’ai juste à cliquer sur le nom pour allumer ou éteindre.

**Comment by NebzHB** [comment]
votre demande est spécifique au plugin eWeLink, vous comprendrez que je ne peux pas faire le support de ce plugin qui n'est pas maintenu par moi...

je vous invite à les contacter à ces fins.

**Comment by dragonjo84** [comment]
Ok j’ai la piste déjà que ça ne vient pas du plugin homebridge. Merci !
